#  Copyright (C) 2021 Xilinx, Inc
#  Copyright (C) 2020 FastML
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

Inputs:
    - j_zlogz
    - j_c1_b0_mmdt
    - j_c1_b1_mmdt
    - j_c1_b2_mmdt
    - j_c2_b1_mmdt
    - j_c2_b2_mmdt
    - j_d2_b1_mmdt
    - j_d2_b2_mmdt
    - j_d2_a1_b1_mmdt
    - j_d2_a1_b2_mmdt
    - j_m2_b1_mmdt
    - j_m2_b2_mmdt
    - j_n2_b1_mmdt
    - j_n2_b2_mmdt
    - j_mass_mmdt
    - j_multiplicity
    
Labels:
    - j_g
    - j_q
    - j_w
    - j_z
    - j_t
    
KerasModel: three_layer_model
KerasModelRetrain: three_layer_model_constraint
KerasLoss: categorical_crossentropy
L1Reg: 0.0001
NormalizeInputs: 1 
InputType: Dense
ApplyPca: false
PcaDimensions: 10

